### ISSUE TITLE
Easy_multi-column_notes not compatible with Blue Topaz theme

### ISSUE THREAD

**Issue by magicdmer** [zamsyt/obsidian-snippets#13]
Columns don't work in reading view, write view ok

**Comment by zamsyt** [comment]
Finally tested. Seems to work fine other than the theme overriding hr color and thus showing when they shouldn't:
![image](https://github.com/zamsyt/obsidian-snippets/assets/102934832/ffc4c35d-348c-4da8-89d9-dcc949c93a67)
Here's a snippet to fix that:
```css
.markdown-rendered hr {
  border-color: var(--hr-color);
}
```
If it's not working at all, you probably don't have the Contextual Typography plugin installed. That's a requirement for reading view to work.
